### ISSUE TITLE
希望能解析qq音乐

### ISSUE THREAD

**Issue by DuCun** [SatoSouta/APlayerAtBottom#3]
好听的音乐网易云没有

**Comment by SatoSouta** [comment]
好的，看看下个版本能不能加入吧（没怎么看issue，狗头）

**Comment by SatoSouta** [comment]
目前这个版本已经可以自定义API，您可以使用自己的音乐API来导入音乐audio数组参数请参照aplayer规范（https://aplayer.js.org）

**Comment by SatoSouta** [comment]
新版本已经添加qq音乐
