### ISSUE TITLE
求助，播放器未加载

### ISSUE THREAD

**Issue by FatDoge** [SatoSouta/APlayerAtBottom#6]
网站链接：status.fatdoge.cn
插件已安装启用并配置歌单id，但是首页没有出现。

**Comment by SatoSouta** [comment]
我看了一下，请您将文件夹授予写入权限，插件根目录未生成settings.json文件则无法加载播放器

**Comment by FatDoge** [comment]
> 我看了一下，请您将文件夹授予写入权限，插件根目录未生成settings.json文件则无法加载播放器

我将整个typhcho目录设置了777还是没有出现，我看network里也没有请求aplayer相关资源，不知道知否是不支持typecho主题`time`

**Comment by FatDoge** [comment]
我用的主题链接 https://www.zmki.cn/4953.html

**Comment by SatoSouta** [comment]
收到反馈了，最近有点忙，等我有时间做个测试适配一下吧。

**Comment by ohmyga233** [comment]
看了下，这是主题的问题，这个主题没有输出 Header 和 Footer。
请手动修改一下 `index.php`，
在 `</body>` 前加上 `<?php $this->footer(); ?>`
在 `</head>` 前加上 `<?php $this->header(); ?>` 即可。
