### ISSUE TITLE
APlayerAtBottom在TeStore中重复出现了2个相同的版本

### ISSUE THREAD

**Issue by jzwalk** [SatoSouta/APlayerAtBottom#7]
因为之前你已经把源码上传到[typecho-fans](https://github.com/typecho-fans/plugins/tree/master/APlayerAtBottom)中，按照[README.md](https://github.com/typecho-fans/plugins/blob/master/README.md)说明，这是决定把APlayerAtBottom交给社区维护了。那么[TESTORE.md](https://github.com/typecho-fans/plugins/blob/master/TESTORE.md)中作为外部插件登记的相同版本APlayerAtBottom就不用再重复列给用户。
所以我把它去除了，然后你又添加回来。。似乎更想APlayerAtBottom作为自主更新的插件指向你这里的原目录？那我就把[README.md](https://github.com/typecho-fans/plugins/blob/master/README.md)中的社区版条目先去掉吧，因为除非这两处源码有差异，否则用户看到2个一样的APlayerAtBottom会很困惑。
或者你误解了，以为把源码放在typecho-fans中才会出现在TeStore，而非愿意交给社区修改？那我就把[typecho-fans](https://github.com/typecho-fans/plugins/tree/master/APlayerAtBottom)里的目录也删除，你还在这里自己的目录里维护就好。请知悉或回复，3Q！:)

**Comment by SatoSouta** [comment]
那就我自己在自己的仓库维护吧

**Comment by jzwalk** [comment]
明白了，OK ;)
